name: Run Unit Tests

on:
  push:
    branches:
      - 'labwork5-471843'
  pull_request:
    branches:
      - 'labwork5-471843'

  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run unittest tests
      run: |
        python -m unittest discover -s tests -p "test.py"
